"""Tests for the redesigned weekly review email.

Covers:
- formatting helpers (HTML → text, fence stripping, list shaping)
- the SQL filter that excludes automated/noreply senders from "real humans"
- the Claude-failure fallback path (still produces a valid email + logs ai_call)
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone
from unittest.mock import AsyncMock, MagicMock, patch

from app.services.polish_service import (
    PolishService,
    _fallback_html_body,
    _format_emails,
    _format_followups,
    _format_meetings,
    _format_people,
    _html_to_text,
    _strip_html_fences,
    _wrap_html_shell,
)


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def test_strip_html_fences_removes_code_block_wrapper():
    assert _strip_html_fences("```html\n<p>hi</p>\n```") == "<p>hi</p>"
    assert _strip_html_fences("```\n<p>hi</p>\n```") == "<p>hi</p>"
    assert _strip_html_fences("<p>plain</p>") == "<p>plain</p>"


def test_html_to_text_renders_bullets_and_strips_tags():
    html_in = "<h3>Header</h3><ul><li>One</li><li>Two</li></ul><p>End.</p>"
    out = _html_to_text(html_in)
    assert "Header" in out
    assert "  • One" in out
    assert "  • Two" in out
    assert "End." in out
    assert "<" not in out and ">" not in out


def test_format_people_uses_name_then_local_part_never_email():
    rows = [
        {"from_email": "sarah@acme.com", "from_name": "Sarah Patel", "n": 4},
        {"from_email": "connor@edra.io", "from_name": None, "n": 2},
    ]
    out = _format_people(rows)
    assert "Sarah Patel" in out
    assert "connor" in out
    # Bare addresses never appear in body text — we only show names / local parts.
    assert "sarah@acme.com" not in out
    assert "connor@edra.io" not in out


def test_format_people_empty():
    assert "no notable" in _format_people([]).lower()


def test_format_emails_caps_subject_and_snippet():
    rows = [{
        "from_name": "Boss",
        "from_email": "boss@corp.com",
        "subject": "S" * 200,
        "snippet": "X" * 400,
        "urgency": "high",
    }]
    out = _format_emails(rows)
    assert "[high]" in out
    assert len(out) < 600  # heavily capped per row


def test_format_followups_renders_commitment():
    rows = [{
        "subject": "Q3 plan",
        "to_email": "sarah@acme.com",
        "follow_up_by": datetime(2026, 5, 1, tzinfo=timezone.utc),
        "auto_draft": "I'll send the technical assessment by Friday.",
    }]
    out = _format_followups(rows)
    assert "sarah" in out
    assert "Q3 plan" in out
    assert "technical assessment" in out


def test_format_meetings_drops_attendee_emails_to_local_parts():
    events = [{
        "title": "Project sync",
        "start": "2026-04-21T15:00:00+00:00",
        "attendees": ["sarah@acme.com", "connor@edra.io"],
    }]
    out = _format_meetings(events)
    assert "Project sync" in out
    assert "sarah" in out and "connor" in out
    assert "@acme.com" not in out


def test_wrap_html_shell_includes_footer_and_escapes_url():
    body = "<p>hi</p>"
    out = _wrap_html_shell(body, 'https://app.test/?q=1&x="2"')
    assert "<p>hi</p>" in out
    assert "Generated by Felix" in out
    # Quotes in the URL should be HTML-escaped so they don't break the href attribute.
    assert '"2"' not in out
    assert "&quot;" in out


def test_fallback_html_body_uses_stats():
    ctx = {"stats": {
        "processed_total": 12,
        "sent_replies": 3,
        "meetings_held": 4,
        "follow_ups_resolved": 1,
    }}
    out = _fallback_html_body(ctx)
    assert "12 emails" in out
    assert "3 Felix-assisted" in out
    assert "4 meetings" in out
    assert "1 follow-ups" in out


# ---------------------------------------------------------------------------
# Real-human contact filter — verifies the SQL excludes automated senders
# ---------------------------------------------------------------------------


async def test_people_query_excludes_automated_and_noreply_senders():
    """The people_rows query must filter category and noreply patterns server-side.

    We verify by inspecting the SQL passed to db.query for the people block.
    """
    svc = PolishService()

    captured: list[str] = []

    async def fake_query(sql, *args, **kwargs):
        captured.append(sql)
        return []

    async def fake_query_one(sql, *args, **kwargs):
        return {}

    with patch("app.services.polish_service.db.query", new=fake_query), \
         patch("app.services.polish_service.db.query_one", new=fake_query_one), \
         patch("app.middleware.auth.get_google_credentials",
               new=AsyncMock(side_effect=Exception("no creds in test"))):
        await svc.gather_weekly_context("user-123")

    people_sql = next(
        (s for s in captured if "GROUP BY e.from_email" in s and "ORDER BY n DESC" in s),
        None,
    )
    assert people_sql is not None, "expected the people aggregation query to run"
    assert "category NOT IN ('automated', 'newsletter')" in people_sql
    for pattern in ("noreply", "no-reply", "notifications@", "invitations@",
                    "alerts@", "donotreply"):
        assert pattern in people_sql, f"missing filter for {pattern}"


# ---------------------------------------------------------------------------
# End-to-end fallback behaviour — Claude failure must still send a valid email
# ---------------------------------------------------------------------------


async def test_generate_weekly_review_falls_back_on_claude_failure():
    svc = PolishService()
    fixed_now = datetime(2026, 4, 27, 18, 0, tzinfo=timezone.utc)
    ctx = {
        "user_id":             "u",
        "display_name":        "Bryn",
        "user_timezone":       "Europe/London",
        "since":               fixed_now - timedelta(days=7),
        "until":               fixed_now,
        "next_until":          fixed_now + timedelta(days=7),
        "category_counts":     {"action_required": 2, "fyi": 5, "newsletter": 30},
        "action_required":     [],
        "sent_replies":        [],
        "unresolved":          [],
        "open_followups":      [],
        "follow_ups_resolved": 1,
        "people":              [],
        "past_meetings":       [],
        "next_meetings":       [],
        "stats": {
            "processed_total": 37, "sent_replies": 2,
            "meetings_held": 3, "follow_ups_resolved": 1,
        },
        "stats_line": "stats line",
    }

    with patch.object(svc, "gather_weekly_context", new=AsyncMock(return_value=ctx)), \
         patch("app.services.polish_service.memory_service.build_memory_context",
               new=AsyncMock(return_value="")), \
         patch("app.services.polish_service._client") as mock_client, \
         patch("app.services.polish_service.log_ai_call",
               new=AsyncMock(return_value=None)) as mock_log:
        mock_client.messages.create = AsyncMock(side_effect=RuntimeError("boom"))
        result = await svc.generate_weekly_review_email("u")

    assert result["subject"].startswith("Felix weekly review")
    assert "<!doctype html>" in result["html"]
    assert "couldn't generate the full briefing" in result["html"]
    assert "37 emails" in result["html"]
    # Plaintext alternative is derived from HTML
    assert "<" not in result["text"]
    assert "37 emails" in result["text"]
    # Failure was logged to ai_calls with success=False
    mock_log.assert_awaited_once()
    assert mock_log.await_args.kwargs["success"] is False
    assert mock_log.await_args.kwargs["feature"] == "weekly_review"


async def test_generate_weekly_review_uses_claude_html_on_success():
    svc = PolishService()
    fixed_now = datetime(2026, 4, 27, 18, 0, tzinfo=timezone.utc)
    ctx = {
        "user_id":             "u",
        "display_name":        "Bryn",
        "user_timezone":       "UTC",
        "since":               fixed_now - timedelta(days=7),
        "until":               fixed_now,
        "next_until":          fixed_now + timedelta(days=7),
        "category_counts":     {},
        "action_required":     [],
        "sent_replies":        [],
        "unresolved":          [],
        "open_followups":      [],
        "follow_ups_resolved": 0,
        "people":              [],
        "past_meetings":       [],
        "next_meetings":       [],
        "stats": {
            "processed_total": 0, "sent_replies": 0,
            "meetings_held": 0, "follow_ups_resolved": 0,
        },
        "stats_line": "0 emails received",
    }
    claude_resp = MagicMock()
    claude_resp.content = [MagicMock(text="<p>Quiet week — nothing pressing.</p>")]

    with patch.object(svc, "gather_weekly_context", new=AsyncMock(return_value=ctx)), \
         patch("app.services.polish_service.memory_service.build_memory_context",
               new=AsyncMock(return_value="")), \
         patch("app.services.polish_service._client") as mock_client, \
         patch("app.services.polish_service.log_ai_call",
               new=AsyncMock(return_value=None)) as mock_log:
        mock_client.messages.create = AsyncMock(return_value=claude_resp)
        result = await svc.generate_weekly_review_email("u")

    assert "Quiet week" in result["html"]
    assert "Quiet week" in result["text"]
    assert mock_log.await_args.kwargs["success"] is True
